spring:
  application:
    name: securescape-backend


  datasource:
    url: jdbc:postgresql://ep-long-lab-ahr27ih6-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: "npg_ux6qoAWt2rsH"
    driver-class-name: org.postgresql.Driver

    # Hikari connection pool configuration
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 10000
      max-lifetime: 30000
      keepalive-time: 15000
      connection-timeout: 30000
      validation-timeout: 5000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC


server:
  port: 8080


# ML Model Configuration
ml:
  model:
    base:
      url: http://localhost:5000

# Gemini API Configuration
gemini:
  api:
    key: ${AIzaSyCIed-Q-WTrzxXn8ucpyhHfb9s13djo7R4}
    model: gemini-1.5-pro
    endpoint: https://generativelanguage.googleapis.com/v1beta/models/


# Logging Configuration (merged into one section)
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
    com:
      securescape: INFO
    org.springframework.web: INFO
